-- This file is autogenerated
-- Pls dont
local info = {
[0x19] =
	{
		["name"] = "Account Management",
		["methods"] = {
[1] = {
				["name"] = "CreateAccount",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "DeleteAccount",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "DisableAccount",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "ChangePassword",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "TestCapability",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetName",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "GetAccountData",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "GetPrivateData",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "GetPublicData",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "GetMultiplePublicData",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "UpdateAccountName",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "UpdateAccountEmail",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "UpdateCustomData",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "FindByNameRegex",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "UpdateAccountExpiryDate",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "UpdateAccountEffectiveDate",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "UpdateStatus",
				["request"] = nil,
				["response"] = nil
			},
			[18] = {
				["name"] = "GetStatus",
				["request"] = nil,
				["response"] = nil
			},
			[19] = {
				["name"] = "GetLastConnectionStats",
				["request"] = nil,
				["response"] = nil
			},
			[20] = {
				["name"] = "ResetPassword",
				["request"] = nil,
				["response"] = nil
			},
			[21] = {
				["name"] = "CreateAccountWithCustomData",
				["request"] = nil,
				["response"] = nil
			},
			[22] = {
				["name"] = "RetrieveAccount",
				["request"] = nil,
				["response"] = nil
			},
			[23] = {
				["name"] = "UpdateAccount",
				["request"] = nil,
				["response"] = nil
			},
			[24] = {
				["name"] = "ChangePasswordByGuest",
				["request"] = nil,
				["response"] = nil
			},
			[25] = {
				["name"] = "FindByNameLike",
				["request"] = nil,
				["response"] = nil
			},
			[26] = {
				["name"] = "CustomCreateAccount",
				["request"] = nil,
				["response"] = nil
			},
			[27] = {
				["name"] = "NintendoCreateAccount",
				["request"] = nil,
				["response"] = nil
			},
			[28] = {
				["name"] = "LookupOrCreateAccount",
				["request"] = nil,
				["response"] = nil
			},
			[29] = {
				["name"] = "DisconnectPrincipal",
				["request"] = nil,
				["response"] = nil
			},
			[30] = {
				["name"] = "DisconnectAllPrincipals",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x0A] =
	{
		["name"] = "Authentication",
		["methods"] = {
[1] = {
				["name"] = "Login",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "LoginEx",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "RequestTicket",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "GetPID",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "GetName",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "LoginWithContext",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x73] =
	{
		["name"] = "Data Store",
		["methods"] = {
[1] = {
				["name"] = "PrepareGetObjectV1",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "PreparePostObjectV1",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "CompletePostObjectV1",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "DeleteObject",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "DeleteObjects",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "ChangeMetaV1",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "ChangeMetasV1",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "GetMeta",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "GetMetas",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "PrepareUpdateObject",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "CompleteUpdateObject",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "SearchObject",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "GetNotificationUrl",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "GetNewArrivedNotificationsV1",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "RateObject",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "GetRating",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "GetRatings",
				["request"] = nil,
				["response"] = nil
			},
			[18] = {
				["name"] = "ResetRating",
				["request"] = nil,
				["response"] = nil
			},
			[19] = {
				["name"] = "ResetRatings",
				["request"] = nil,
				["response"] = nil
			},
			[20] = {
				["name"] = "GetSpecificMetaV1",
				["request"] = nil,
				["response"] = nil
			},
			[21] = {
				["name"] = "PostMetaBinary",
				["request"] = nil,
				["response"] = nil
			},
			[22] = {
				["name"] = "TouchObject",
				["request"] = nil,
				["response"] = nil
			},
			[23] = {
				["name"] = "GetRatingWithLog",
				["request"] = nil,
				["response"] = nil
			},
			[24] = {
				["name"] = "PreparePostObject",
				["request"] = nil,
				["response"] = nil
			},
			[25] = {
				["name"] = "PrepareGetObject",
				["request"] = nil,
				["response"] = nil
			},
			[26] = {
				["name"] = "CompletePostObject",
				["request"] = nil,
				["response"] = nil
			},
			[27] = {
				["name"] = "GetNewArrivedNotifications",
				["request"] = nil,
				["response"] = nil
			},
			[28] = {
				["name"] = "GetSpecificMeta",
				["request"] = nil,
				["response"] = nil
			},
			[29] = {
				["name"] = "GetPersistenceInfo",
				["request"] = nil,
				["response"] = nil
			},
			[30] = {
				["name"] = "GetPersistenceInfos",
				["request"] = nil,
				["response"] = nil
			},
			[31] = {
				["name"] = "PerpetuateObject",
				["request"] = nil,
				["response"] = nil
			},
			[32] = {
				["name"] = "UnperpetuateObject",
				["request"] = nil,
				["response"] = nil
			},
			[33] = {
				["name"] = "PrepareGetObjectOrMetaBinary",
				["request"] = nil,
				["response"] = nil
			},
			[34] = {
				["name"] = "GetPasswordInfo",
				["request"] = nil,
				["response"] = nil
			},
			[35] = {
				["name"] = "GetPasswordInfos",
				["request"] = nil,
				["response"] = nil
			},
			[36] = {
				["name"] = "GetMetasMultipleParam",
				["request"] = nil,
				["response"] = nil
			},
			[37] = {
				["name"] = "CompletePostObjects",
				["request"] = nil,
				["response"] = nil
			},
			[38] = {
				["name"] = "ChangeMeta",
				["request"] = nil,
				["response"] = nil
			},
			[39] = {
				["name"] = "ChangeMetas",
				["request"] = nil,
				["response"] = nil
			},
			[40] = {
				["name"] = "RateObjects",
				["request"] = nil,
				["response"] = nil
			},
			[41] = {
				["name"] = "PostMetaBinaryWithDataId",
				["request"] = nil,
				["response"] = nil
			},
			[42] = {
				["name"] = "PostMetaBinariesWithDataId",
				["request"] = nil,
				["response"] = nil
			},
			[43] = {
				["name"] = "RateObjectWithPosting",
				["request"] = nil,
				["response"] = nil
			},
			[44] = {
				["name"] = "RateObjectsWithPosting",
				["request"] = nil,
				["response"] = nil
			},
			[45] = {
				["name"] = "GetObjectInfos",
				["request"] = nil,
				["response"] = nil
			},
			[46] = {
				["name"] = "SearchObjectLight",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x65] =
	{
		["name"] = "Friends 3DS",
		["methods"] = {
[1] = {
				["name"] = "UpdateProfile",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "UpdateMii",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "UpdateMiiList",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "UpdatePlayedGames",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "UpdatePreference",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetFriendMii",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "GetFriendRelationships",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "AddFriendByPrincipalID",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "GetAllFriends",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "SyncFriend",
				["request"] = nil,
				["response"] = nil
			},
			[18] = {
				["name"] = "UpdatePresence",
				["request"] = nil,
				["response"] = nil
			},
			[19] = {
				["name"] = "UpdateFavoriteGameKey",
				["request"] = nil,
				["response"] = nil
			},
			[20] = {
				["name"] = "UpdateComment",
				["request"] = nil,
				["response"] = nil
			},
			[21] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[22] = {
				["name"] = "GetFriendPresence",
				["request"] = nil,
				["response"] = nil
			},
			[23] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[24] = {
				["name"] = "GetFriendPicture",
				["request"] = nil,
				["response"] = nil
			},
			[25] = {
				["name"] = "GetFriendPersistentInfo",
				["request"] = nil,
				["response"] = nil
			},
			[26] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x66] =
	{
		["name"] = "Friends Wii U",
		["methods"] = {
[1] = {
				["name"] = "GetAllInformation",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "UpdatePresence",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[18] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[19] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			[20] = {
				["name"] = "?",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x14] =
	{
		["name"] = "Friends",
		["methods"] = {
[1] = {
				["name"] = "AddFriend",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "AddFriendByName",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "AddFriendWithDetails",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "AddFriendByNameWithDetails",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "AcceptFriendship",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "DeclineFriendship",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "BlackList",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "BlackList",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "ClearRelationship",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "UpdateDetails",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "GetList",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "GetDetailedList",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "GetRelationships",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x12] =
	{
		["name"] = "Health",
		["methods"] = {
[1] = {
				["name"] = "PingDaemon",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "PingDatabase",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "RunSanityCheck",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "FixSanityErrors",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x32] =
	{
		["name"] = "Match Making Ext",
		["methods"] = {
[1] = {
				["name"] = "EndParticipation",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "GetParticipants",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "GetDetailedParticipants",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "GetParticipantsURLs",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "GetGatheringRelations",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "DeleteFromDeletions",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x15] =
	{
		["name"] = "Match Making",
		["methods"] = {
[1] = {
				["name"] = "RegisterGathering",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "UnregisterGathering",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "UnregisterGatherings",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "UpdateGathering",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "Invite",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "AcceptInvitation",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "DeclineInvitation",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "CancelInvitation",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "GetInvitationsSent",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "GetInvitationsReceived",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "Participate",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "CancelParticipation",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "GetParticipants",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "AddParticipants",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "GetDetailedParticipants",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "GetParticipantsURLs",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "FindByType",
				["request"] = nil,
				["response"] = nil
			},
			[18] = {
				["name"] = "FindByDescription",
				["request"] = nil,
				["response"] = nil
			},
			[19] = {
				["name"] = "FindByDescriptionRegex",
				["request"] = nil,
				["response"] = nil
			},
			[20] = {
				["name"] = "FindByID",
				["request"] = nil,
				["response"] = nil
			},
			[21] = {
				["name"] = "FindBySingleID",
				["request"] = nil,
				["response"] = nil
			},
			[22] = {
				["name"] = "FindByOwner",
				["request"] = nil,
				["response"] = nil
			},
			[23] = {
				["name"] = "FindByParticipants",
				["request"] = nil,
				["response"] = nil
			},
			[24] = {
				["name"] = "FindInvitations",
				["request"] = nil,
				["response"] = nil
			},
			[25] = {
				["name"] = "FindBySQLQuery",
				["request"] = nil,
				["response"] = nil
			},
			[26] = {
				["name"] = "LaunchSession",
				["request"] = nil,
				["response"] = nil
			},
			[27] = {
				["name"] = "UpdateSessionURL",
				["request"] = nil,
				["response"] = nil
			},
			[28] = {
				["name"] = "GetSessionURL",
				["request"] = nil,
				["response"] = nil
			},
			[29] = {
				["name"] = "GetState",
				["request"] = nil,
				["response"] = nil
			},
			[30] = {
				["name"] = "SetState",
				["request"] = nil,
				["response"] = nil
			},
			[31] = {
				["name"] = "ReportStats",
				["request"] = nil,
				["response"] = nil
			},
			[32] = {
				["name"] = "GetStats",
				["request"] = nil,
				["response"] = nil
			},
			[33] = {
				["name"] = "DeleteGathering",
				["request"] = nil,
				["response"] = nil
			},
			[34] = {
				["name"] = "GetPendingDeletions",
				["request"] = nil,
				["response"] = nil
			},
			[35] = {
				["name"] = "DeleteFromDeletions",
				["request"] = nil,
				["response"] = nil
			},
			[36] = {
				["name"] = "MigrateGatheringOwnershipV1",
				["request"] = nil,
				["response"] = nil
			},
			[37] = {
				["name"] = "FindByDescriptionLike",
				["request"] = nil,
				["response"] = nil
			},
			[38] = {
				["name"] = "RegisterLocalURL",
				["request"] = nil,
				["response"] = nil
			},
			[39] = {
				["name"] = "RegisterLocalURLs",
				["request"] = nil,
				["response"] = nil
			},
			[40] = {
				["name"] = "UpdateSessionHostV1",
				["request"] = nil,
				["response"] = nil
			},
			[41] = {
				["name"] = "GetSessionURLs",
				["request"] = nil,
				["response"] = nil
			},
			[42] = {
				["name"] = "UpdateSessionHost",
				["request"] = nil,
				["response"] = nil
			},
			[43] = {
				["name"] = "UpdateGatheringOwnership",
				["request"] = nil,
				["response"] = nil
			},
			[44] = {
				["name"] = "MigrateGatheringOwnership",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x6D] =
	{
		["name"] = "Matchmake Extension",
		["methods"] = {
[1] = {
				["name"] = "CloseParticipation",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "OpenParticipation",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "AutoMatchmake_Postpone",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "BrowseMatchmakeSession",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "BrowseMatchmakeSessionWithHostUrls",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "CreateMatchmakeSession",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "JoinMatchmakeSession",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "ModifyCurrentGameAttribute",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "UpdateNotificationData",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "GetFriendNotificationData",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "UpdateApplicationBuffer",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "UpdateMatchmakeSessionAttribute",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "GetlstFriendNotificationData",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "UpdateMatchmakeSession",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "AutoMatchmakeWithSearchCriteria_Postpone",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "GetPlayingSession",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "CreateCommunity",
				["request"] = nil,
				["response"] = nil
			},
			[18] = {
				["name"] = "UpdateCommunity",
				["request"] = nil,
				["response"] = nil
			},
			[19] = {
				["name"] = "JoinCommunity",
				["request"] = nil,
				["response"] = nil
			},
			[20] = {
				["name"] = "FindCommunityByGatheringId",
				["request"] = nil,
				["response"] = nil
			},
			[21] = {
				["name"] = "FindOfficialCommunity",
				["request"] = nil,
				["response"] = nil
			},
			[22] = {
				["name"] = "FindCommunityByParticipant",
				["request"] = nil,
				["response"] = nil
			},
			[23] = {
				["name"] = "UpdatePrivacySetting",
				["request"] = nil,
				["response"] = nil
			},
			[24] = {
				["name"] = "GetMyBlackList",
				["request"] = nil,
				["response"] = nil
			},
			[25] = {
				["name"] = "AddToBlackList",
				["request"] = nil,
				["response"] = nil
			},
			[26] = {
				["name"] = "RemoveFromBlackList",
				["request"] = nil,
				["response"] = nil
			},
			[27] = {
				["name"] = "ClearMyBlackList",
				["request"] = nil,
				["response"] = nil
			},
			[28] = {
				["name"] = "ReportViolation",
				["request"] = nil,
				["response"] = nil
			},
			[29] = {
				["name"] = "IsViolationUser",
				["request"] = nil,
				["response"] = nil
			},
			[30] = {
				["name"] = "JoinMatchmakeSessionEx",
				["request"] = nil,
				["response"] = nil
			},
			[31] = {
				["name"] = "GetSimplePlayingSession",
				["request"] = nil,
				["response"] = nil
			},
			[32] = {
				["name"] = "GetSimpleCommunity",
				["request"] = nil,
				["response"] = nil
			},
			[33] = {
				["name"] = "AutoMatchmakeWithGatheringId_Postpone",
				["request"] = nil,
				["response"] = nil
			},
			[34] = {
				["name"] = "UpdateProgressScore",
				["request"] = nil,
				["response"] = nil
			},
			[35] = {
				["name"] = "DebugNotifyEvent",
				["request"] = nil,
				["response"] = nil
			},
			[36] = {
				["name"] = "GenerateMatchmakeSessionSystemPassword",
				["request"] = nil,
				["response"] = nil
			},
			[37] = {
				["name"] = "ClearMatchmakeSessionSystemPassword",
				["request"] = nil,
				["response"] = nil
			},
			[38] = {
				["name"] = "CreateMatchmakeSessionWithParam",
				["request"] = nil,
				["response"] = nil
			},
			[39] = {
				["name"] = "JoinMatchmakeSessionWithParam",
				["request"] = nil,
				["response"] = nil
			},
			[40] = {
				["name"] = "AutoMatchmakeWithParam_Postpone",
				["request"] = nil,
				["response"] = nil
			},
			[41] = {
				["name"] = "FindMatchmakeSessionByGatheringIdDetail",
				["request"] = nil,
				["response"] = nil
			},
			[42] = {
				["name"] = "BrowseMatchmakeSessionNoHolder",
				["request"] = nil,
				["response"] = nil
			},
			[43] = {
				["name"] = "BrowseMatchmakeSessionWithHostUrlsNoHolder",
				["request"] = nil,
				["response"] = nil
			},
			[44] = {
				["name"] = "UpdateMatchmakeSessionPart",
				["request"] = nil,
				["response"] = nil
			},
			[45] = {
				["name"] = "RequestMatchmaking",
				["request"] = nil,
				["response"] = nil
			},
			[46] = {
				["name"] = "WithdrawMatchmaking",
				["request"] = nil,
				["response"] = nil
			},
			[47] = {
				["name"] = "WithdrawMatchmakingAll",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x200] =
	{
		["name"] = "Mesh Protocol",
		["methods"] = {
[1] = {
				["name"] = "Join request",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "Join response",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "Leave request",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "Leave response",
				["request"] = nil,
				["response"] = nil
			},
			[16] = {
				["name"] = "Destroy mesh",
				["request"] = nil,
				["response"] = nil
			},
			[17] = {
				["name"] = "Destroy response",
				["request"] = nil,
				["response"] = nil
			},
			[32] = {
				["name"] = "Update mesh",
				["request"] = nil,
				["response"] = nil
			},
			[33] = {
				["name"] = "Kickout notice",
				["request"] = nil,
				["response"] = nil
			},
			[34] = {
				["name"] = "Dummy message",
				["request"] = nil,
				["response"] = nil
			},
			[36] = {
				["name"] = "Connection failure notice",
				["request"] = nil,
				["response"] = nil
			},
			[64] = {
				["name"] = "Greeting",
				["request"] = nil,
				["response"] = nil
			},
			[65] = {
				["name"] = "Migration finish",
				["request"] = nil,
				["response"] = nil
			},
			[66] = {
				["name"] = "Greeting response",
				["request"] = nil,
				["response"] = nil
			},
			[68] = {
				["name"] = "Migration start",
				["request"] = nil,
				["response"] = nil
			},
			[72] = {
				["name"] = "Migration response",
				["request"] = nil,
				["response"] = nil
			},
			[73] = {
				["name"] = "Multi migration start",
				["request"] = nil,
				["response"] = nil
			},
			[74] = {
				["name"] = "Multi migration rank decision",
				["request"] = nil,
				["response"] = nil
			},
			[128] = {
				["name"] = "Connection report",
				["request"] = nil,
				["response"] = nil
			},
			[129] = {
				["name"] = "Relay route directions",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x1B] =
	{
		["name"] = "Message Delivery",
		["methods"] = {
[1] = {
				["name"] = "DeliverMessage",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x17] =
	{
		["name"] = "Messaging",
		["methods"] = {
[1] = {
				["name"] = "DeliverMessage",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "GetNumberOfMessages",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "GetMessagesHeaders",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "RetrieveAllMessagesWithinRange",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "RetrieveMessages",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "DeleteMessages",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "DeleteAllMessages",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x13] =
	{
		["name"] = "Monitoring",
		["methods"] = {
[1] = {
				["name"] = "PingDaemon",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "GetClusterMembers",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x400] =
	{
		["name"] = "NAT Traversal",
		["methods"] = {
[1] = {
				["name"] = "Probe request",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "Probe reply",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "Dummy packet",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x03] =
	{
		["name"] = "NAT Traversal",
		["methods"] = {
[1] = {
				["name"] = "RequestProbeInitiation",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "InitiateProbe",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "RequestProbeInitiationExt",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "ReportNATTraversalResult",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "ReportNATProperties",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetRelaySignatureKey",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "ReportNATTraversalResultDetail",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},

[0x64] =
	{
		["name"] = "Nintendo Notifications",
		["methods"] = {
[1] = {
				["name"] = "ProcessNintendoNotificationEvent",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "ProcessNintendoNotificationEvent (iosu)",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x0E] =
	{
		["name"] = "Notifications",
		["methods"] = {
[1] = {
				["name"] = "ProcessNotificationEvent",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x18] =
	{
		["name"] = "Persistent Store",
		["methods"] = {
[1] = {
				["name"] = "FindByGroup",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "InsertItem",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "RemoveItem",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "GetItem",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "InsertCustomItem",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetCustomItem",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "FindItemsBySQLQuery",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x7A] =
	{
		["name"] = "Ranking 2",
		["methods"] = {
[1] = {
				["name"] = "PutScore",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "GetCommonData",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "PutCommonData",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "DeleteCommonData",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "GetRanking",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetRankingByPrincipalId",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "GetCategorySetting",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x70] =
	{
		["name"] = "Ranking",
		["methods"] = {
[1] = {
				["name"] = "UploadScore",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "DeleteScore",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "DeleteAllScores",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "UploadCommonData",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "DeleteCommonData",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetCommonData",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "ChangeAttributes",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "ChangeAllAttributes",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "GetRanking",
				["request"] = nil,
				["response"] = nil
			},
			[10] = {
				["name"] = "GetApproxOrder",
				["request"] = nil,
				["response"] = nil
			},
			[11] = {
				["name"] = "GetStats",
				["request"] = nil,
				["response"] = nil
			},
			[12] = {
				["name"] = "GetRankingByPIDList",
				["request"] = nil,
				["response"] = nil
			},
			[13] = {
				["name"] = "GetRankingByUniqueIdList",
				["request"] = nil,
				["response"] = nil
			},
			[14] = {
				["name"] = "GetCachedTopXRanking",
				["request"] = nil,
				["response"] = nil
			},
			[15] = {
				["name"] = "GetCachedTopXRankings",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x01] =
	{
		["name"] = "Remote Log Device",
		["methods"] = {
[1] = {
				["name"] = "Log",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x0B] =
	{
		["name"] = "Secure Connection",
		["methods"] = {
[1] = {
				["name"] = "Register",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "RequestConnectionData",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "RequestUrls",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "RegisterEx",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "TestConnectivity",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "UpdateURLs",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "ReplaceURL",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "SendReport",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x10] =
	{
		["name"] = "Simple Authentication",
		["methods"] = {
[1] = {
				["name"] = "Authenticate",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "LoginWithToken",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "LoginWithTokenEx",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "Login",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "LoginWithSubAccount",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "Register",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "RegisterEx",
				["request"] = nil,
				["response"] = nil
			},
			[8] = {
				["name"] = "LoginWithTokenCafe",
				["request"] = nil,
				["response"] = nil
			},
			[9] = {
				["name"] = "LoginWithTokenCafeEx",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x100] =
	{
		["name"] = "Station Protocol",
		["methods"] = {
[1] = {
				["name"] = "Connection request",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "Connection response",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "Disconnection request",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "Disconnection response",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "Ack",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "Relay connection request",
				["request"] = nil,
				["response"] = nil
			},
			[7] = {
				["name"] = "Relay connection response",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
[0x6E] =
	{
		["name"] = "Utility",
		["methods"] = {
[1] = {
				["name"] = "AcquireNexUniqueId",
				["request"] = nil,
				["response"] = nil
			},
			[2] = {
				["name"] = "AcquireNexUniqueIdWithPassword",
				["request"] = nil,
				["response"] = nil
			},
			[3] = {
				["name"] = "AssociateNexUniqueIdWithMyPrincipalId",
				["request"] = nil,
				["response"] = nil
			},
			[4] = {
				["name"] = "AssociateNexUniqueIdsWithMyPrincipalId",
				["request"] = nil,
				["response"] = nil
			},
			[5] = {
				["name"] = "GetAssociatedNexUniqueIdWithMyPrincipalId",
				["request"] = nil,
				["response"] = nil
			},
			[6] = {
				["name"] = "GetAssociatedNexUniqueIdsWithMyPrincipalId",
				["request"] = nil,
				["response"] = nil
			},
			
		}
	},
}
return info